name: BackToBodyPlugin
main: me.shanodis.BackToBodyPlugin.Main
version: 1.0
commands:
  back:
    description: The command will teleport a player to it's body. It can be executed when the player has died.
